placeObjects();

    LeftWall(35,  200, "images/Art_01.jpg", "audio/Art_01.mp3", "Gwamaka Mwalemba, a legend among students for all the wrong reasons. His tests were like mazes, leading many to the dreaded supplementary exams. He allowed cheat sheets, but they were like maps to nowhere. Ironically, the painting, originally owned by Leonardo, now resides at UCT, brought to Cape Town by Van Riebeek.");
    LeftWall(22,  125, "images/Art_02.jpg", "audio/Art_02.mp3", "This famous photograph depicts the tragic scene following the brutal killing of Hector Pieterson, a 13-year-old student, during the Soweto Uprising in apartheid South Africa on June 16, 1976. The photograph was taken by Sam Nzima, a photographer for a Johannesburg-based newspaper. It powerfully captures the moment when Hector's devastated friend, Mbuyisa Makhubo, and another distraught student carried his fatally wounded body after he was gunned down by South African police who opened fire on black students protesting the enforced use of Afrikaans in black township schools. Nzima's photograph acted as a wake-up call to the world about the brutal reality of apartheid's oppression of black South Africans. It became an iconic image in the anti-apartheid movement and a rallying cry against the injustices of the racist regime. This searing visual testimony of senseless violence against innocent children brought renewed focus on dismantling the institutionalized system of racial segregation and discrimination in South Africa.");
    LeftWall(20,   50, "images/Art_03.jpg", "audio/Art_03.mp3", "The release of the iconic Nelson Mandela picture is a pivotal moment in history, capturing Mandela's liberation after 27 years of imprisonment under apartheid rule in South Africa. The image was taken on February 11, 1990, by Louise Gubb, a photographer for the Associated Press, outside of Victor Verster Prison in Paarl, South Africa.");
    LeftWall(46,  -50, "images/Art_04.jpg", "audio/Art_04.mp3", "The picture of the first time black people voted in South Africa captures the historic moment of the general elections on April 27, 1994. It signifies the end of apartheid and the dawn of democracy in the country. The image symbolizes the long-awaited realization of equality and the triumph of the human spirit over oppression.");
    LeftWall(28, -160, "images/Art_05.jpg", "audio/Art_05.mp3", "In this iconic portrayal, Nelson Mandela, the revered leader of South Africa, stands alongside the victorious team, encapsulating the spirit of unity and triumph. The 1996 tournament, hosted by South Africa, marked a historic moment as it was the first AFCON held after the end of apartheid.");

    FrontWall(40, -320, "images/Art_06.jpg", "audio/Art_06.mp3", "The picture of the Springboks winning their fourth Rugby World Cup represents an extraordinary feat in sports history. It showcases the relentless determination and skill of the team, illustrating their unmatched prowess on the rugby field. Their victory marks a significant milestone, solidifying their legacy as one of the most formidable teams in the sport. It's a moment that will be remembered and celebrated by fans worldwide, inspiring future generations of rugby players to strive for greatness.");
    FrontWall(27, -250, "images/Art_07.jpg", "audio/Art_07.mp3", "The image of Siphiwe Tshabalala's opening goal in the 2010 FIFA World Cup is iconic and etched into the memories of football fans around the globe. In that moment, as Tshabalala unleashed a thunderous strike into the back of the net, the entire nation of South Africa erupted in joy and pride. ");
    FrontWall(53, -170, "images/Art_08.jpg", "audio/Art_08.mp3", "San rock art is a collection of ancient drawings and engravings found in caves and overhangs in Southern Africa. The art depicts the San's daily life, hunting, rituals, spiritual beliefs, and wildlife, and is considered one of the earliest forms of human creativity.");
    FrontWall(47,  -80, "images/Art_09.jpg", "audio/Art_09.mp3", "The painting depicts Sarah Baartman, also known as the Hottentot Venus, a Khoikhoi woman who was exhibited in 19th-century Europe due to her large buttocks. Her story highlights colonial exploitation, racism, and the objectification of African women. The painting prompts reflection on historical injustices and the importance of human dignity.");
    FrontWall(30,   60, "images/Art_10.jpg", "audio/Art_10.mp3", "The painting captures a snapshot of the 1976 Soweto Uprising, a pivotal moment in South Africa's history where thousands of black students protested against the Afrikaans Medium Decree. The artwork immortalizes the bravery and resilience of the youth, shedding light on their struggle for quality education and liberation from apartheid.");

    RightWall(48,   55, "images/Art_11.jpg", "audio/Art_11.mp3", "The painting depicts the historic release of Nelson Mandela from prison in 1990, marking the end of 27 years of incarceration and the beginning of a new era in South Africa. The artwork captures Mandela's iconic fist raised in triumph and the overwhelming joy and hope of the people, symbolizing the triumph of the human spirit over oppression.");
    RightWall(53,  135, "images/Art_12.jpg", "audio/Art_12.mp3", "The painting portrays the unification of South Africa's diverse communities, represented by various cultural symbols and figures coming together. It embodies the vision of a 'Rainbow Nation' championed by Nelson Mandela, emphasizing unity, reconciliation, and the celebration of diversity. The artwork serves as a powerful reminder of the ongoing journey towards a more inclusive and harmonious society.");
    RightWall(25,  225, "images/Art_13.jpg", "audio/Art_13.mp3", "The image of Nelson Mandela and F.W. de Klerk shaking hands after the latter's historic speech in 1990 signifies a turning point in South African history. De Klerk's announcement of the unbanning of the ANC and the release of Mandela marked the beginning of the end of apartheid. This powerful gesture of reconciliation between the two leaders symbolizes the hope and possibility of a peaceful transition to democracy.");
    RightWall(47,  300, "images/Art_14.jpg", "audio/Art_14.mp3", "The painting of Desmond Tutu, affectionately known as 'The Arch,' captures his joyous spirit and unwavering commitment to justice. Tutu, a prominent anti-apartheid and human rights activist, is depicted with his iconic infectious smile. The artwork celebrates his role in South Africa's journey towards equality and his enduring legacy as a beacon of hope and compassion.");
    RightWall(42,  375, "images/Art_15.jpg", "audio/Art_15.mp3", "The image of the 1995 Rugby World Cup Final captures a historic moment of national unity and pride in South Africa. Hosted in Johannesburg, the tournament saw the Springboks, led by captain Francois Pienaar, win their first Rugby World Cup. The photograph famously depicts Nelson Mandela, wearing a Springbok jersey, presenting the Webb Ellis Cup to Pienaar. This powerful gesture symbolized the potential for reconciliation and unity in the post-apartheid era. The victory not only marked a significant achievement in sports but also became a symbol of hope and healing for a nation emerging from decades of division and oppression.");

    BackWall(10,   90, "images/Art_16.jpg", "audio/Art_16.mp3", "The image of the Union Buildings, located in Pretoria, South Africa, represents a significant historical landmark in the country's history. The Union Buildings serve as the official seat of the South African government and the offices of the President of South Africa. This iconic structure symbolizes the country's transition from colonial rule to a democratic republic. The Union Buildings have witnessed numerous important events, including the inauguration of Nelson Mandela as South Africa's first black President in 1994. The architecture itself reflects the blending of different styles, symbolizing the diverse and multicultural nature of the nation. As a prominent feature of the Pretoria skyline, the Union Buildings stand as a testament to South Africa's journey towards freedom, equality, and democracy.");
    BackWall(40,   20, "images/Art_17.jpg", "audio/Art_17.mp3", "The image of the South African flag represents a powerful symbol of unity and hope for a nation that has overcome decades of apartheid and racial division. The flag, adopted in 1994, features six colors, each with its own significance. The black, green, and yellow colors are derived from the flag of the African National Congress (ANC), symbolizing the country's black population and their struggles for freedom. The red, blue, and white colors reflect the flags of both the Netherlands and the United Kingdom, representing the country's colonial history. The 'Y' shape signifies the convergence of diverse elements within South African society, moving forward in unity. The flag is a visual reminder of the country's commitment to reconciliation, diversity, and progress. It serves as a beacon of hope, symbolizing the aspirations and dreams of all South Africans for a better future.");
    BackWall(36, -110, "images/Art_18.jpg", "audio/Art_18.mp3", "The painting portrays the vibrant streets of Johannesburg, a bustling metropolis and the economic heart of South Africa. The artwork captures the city's dynamic energy, reflecting its diverse cultures, thriving arts scene, and historical significance. Known as 'Joburg' or 'Jozi,' Johannesburg is a symbol of resilience and progress. The city's history is deeply intertwined with the country's journey through apartheid and its emergence as a democratic nation. Johannesburg's skyline, marked by towering skyscrapers and iconic landmarks, represents the growth and transformation of South Africa. The painting serves as a tribute to the spirit of Johannesburg, embodying the hopes and dreams of its inhabitants. It celebrates the city's unique blend of tradition and modernity, making it a vibrant and essential part of South Africa's identity.");
    BackWall(40, -260, "images/Art_19.jpg", "audio/Art_19.mp3", "The photograph captures a poignant moment in history when Nelson Mandela, South Africa's first black President, cast his vote for the first time in the country's democratic elections. This event, which took place on April 27, 1994, marked the end of apartheid and the dawn of a new era of freedom and equality. Mandela's act of voting was a powerful symbol of the struggles and sacrifices made by millions of South Africans in their fight for liberation. The image of Mandela voting serves as an enduring reminder of the importance of democracy, the right to vote, and the ongoing journey towards justice and equality.");
    BackWall(45, -380, "images/Art_20.jpg", "audio/Art_20.mp3", "The painting depicts the struggle for freedom and equality in South Africa, highlighting the sacrifices and resilience of those who fought against apartheid. The artwork captures the spirit of resistance, portraying key moments and figures that contributed to the nation's liberation. It serves as a tribute to the countless individuals who dedicated their lives to achieving justice and human rights. The painting is a powerful reminder of the country's turbulent past and the enduring hope for a future where all people can live in dignity and harmony.");
renderRoom();

welcomeMessage("Welcome.mp3", "Welcome to the virtual art museum developed by Team 12. Click or tap on an artwork to zoom in and learn its history.");